<div class="admin-controls">
    <!-- SERIES -->
     <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownSeries" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Series
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownSeries">
        <li><a href="<?php echo $this->url('admin', array('action'=>'add', 'type' => 'serie'));?> ">Add new serie</a></li>
        <li><a href="<?php echo $this->url('admin', array('action'=>'search'));?> ">Search serie</a></li>
      </ul>
    </div>
    <!-- MOODS -->
     <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownSeries" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Moods
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownSeries">
        <li><a href="<?php echo $this->url('admin');?>#moods ">List All moods</a></li>
        <li><a href="<?php echo $this->url('mood', array('action'=>'add', 'type' => 'mood'));?> ">Add new Mood</a></li>
      </ul>
    </div>
</div>

<h1><?php echo "Liste des Series" ?></h1>
 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($series as $serie) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($serie->titre);?></td>
     <td><?php echo $this->escapeHtml($serie->synopsys);?></td>
     <td><?php echo $this->escapeHtml($serie->anneeDebut);?></td>
     <td><?php echo $this->escapeHtml($serie->anneeFin);?></td>
     <td><?php echo $this->escapeHtml($serie->image);?></td>
     <td>
        <a href="<?php echo $this->url('admin',
             array('action'=>'details', 'id' => $serie->id));?>">Details</a>
         <a href="<?php echo $this->url('admin',
             array('action'=>'edit', 'id' => $serie->id));?>">Edit</a>
         <a href="<?php echo $this->url('admin',
             array('action'=>'delete', 'id' => $serie->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>


<hr>

<h2 id="moods">Liste des Moods</h2>
<div class="moods-list">
 <?php foreach ($moods as $mood) : ?>

    <p>
        <a href="<?php echo $this->url('mood',
             array('action'=>'details', 'id' => $mood->id));?>"><?php echo $this->escapeHtml($mood->nom);?>
        </a>
    </p>
    
<?php endforeach; ?>
</div>

  <a href="<?php echo $this->url('admin');?>">Back To Admin Index
 </a>