 <p class="admin-button-serie">
     <a class="btn btn-primary" role="button" href="<?php echo $this->url('admin', array('action'=>'add'));?> ">Add new serie</a>
     <a class="btn btn-primary" role="button" href="<?php echo $this->url('admin', array('action'=>'search'));?> ">Search serie</a>
 </p>
<!--  <p class="admin-button-user">
     <a class="btn btn-primary" role="button" href="<?php echo $this->url('admin', array('action'=>'add'));?> ">Add new user</a>
     <a class="btn btn-primary" role="button" href="<?php echo $this->url('admin', array('action'=>'search'));?> ">Search user</a>
 </p> -->

<h1><?php echo "Liste des Series" ?></h1>
 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($series as $serie) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($serie->titre);?></td>
     <td><?php echo $this->escapeHtml($serie->synopsys);?></td>
     <td><?php echo $this->escapeHtml($serie->anneeDebut);?></td>
     <td><?php echo $this->escapeHtml($serie->anneeFin);?></td>
     <td><?php echo $this->escapeHtml($serie->image);?></td>
     <td>
        <a href="<?php echo $this->url('admin',
             array('action'=>'details', 'id' => $serie->id));?>">Details</a>
         <a href="<?php echo $this->url('admin',
             array('action'=>'edit', 'id' => $serie->id));?>">Edit</a>
         <a href="<?php echo $this->url('admin',
             array('action'=>'delete', 'id' => $serie->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>